### ISSUE TITLE
Update submit a training

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#11]
There is a new page to explain what submitting a session is. Should include a bit about platinum sponsors getting first dibs. This page gets linked to from the training block on the home page.

https://backend2019.texascamp.org/submit-training

**Comment by ccjjmartin** [comment]
@rocketeerbkw Let me know your thoughts on the session workflow also allowing trainings to be submitted.  Someone could miss the separate training page, how do you feel about adding training information to the sessions information page and linking the trainings link on the home page to that page so that no one misses it?

**Comment by rocketeerbkw** [comment]
I just linked to the two pages on the session form, problem solved. I also updated the training page, if you sign off we can close this.

**Comment by ccjjmartin** [comment]
@rocketeerbkw Looks perfect.  Closing.
