### ISSUE TITLE
Can only see lightning bolt on Pantheon symbol at bottom

### ISSUE THREAD

**Issue by irmamartin** [TexasCamp/2019.texascamp.org#21]
The Pantheon icon doesn’t show up as well as Amazee at the bottom of the website.  Y’all might want to take a look at that.  Especially on the bottom.  Black against black.  To be honest, I just saw the lightning bolt and almost disregarded it. (I put this on the Slack texas-camp-website channel too.) 
Thanks

**Comment by rocketeerbkw** [comment]
![image](https://user-images.githubusercontent.com/92499/63291097-84bf9680-c288-11e9-9f28-5bce558fba4a.png)

Bug: Logos in the footer are converted to greyscale. If an image has the color black, it will stay black which creates dark-on-dark visibility issue.

Possible fixes (in order of least difficulty):
- ~~Don't greyscale images at all. This will make the amazee labs logo turn back to dark blue, which will be hard to see. This will make the pantheon logo bolt be yellow, but the rest will stay black, which is hard to see.~~ This actually doesn't fix the bug at all
- Photoshop the pantheon logo so that it doesn't contain true black. It will look black on the regular sponsors page, and look grey in the footer
- Add a background color, similar to the sponsors page
- Add a second image field to sponsor content type and create footer compatible logos for both sponsors
- Other?

**Comment by ccjjmartin** [comment]
Pantheon requested the white image, problem solved.
