### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2019.texascamp.org#51]
Do we have one?

**Comment by WidgetsBurritos** [comment]
I don't see the connection occurring, so I'm assuming no.   
I'd say if we're going to add one in, we should install it via Google Tag Manager instead of Google Analytics directly. 

As we are dealing with a react app, with its own routing rules, there may be some need for customization, and GTM provides a mechanism for that.

**Comment by WidgetsBurritos** [comment]
I've pushed PR #52 to add this in.

**Comment by WidgetsBurritos** [comment]
#52 is merged in so closing this issue
